config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: 'contact#index'
  get '/breeding_process', to: 'breeding_process#index'  
  get '/dear_parents', to: 'dear_parents#index'
  get '/history', to: 'history#index'
  get '/upbringing', to: 'upbringing#index'
  get 'parents', to: 'parents#index'
  root "pages#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ActiveRecord::Base
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	belongs_to :partner
end

app/models/partner.rb
class Partner < ActiveRecord::Base
	# def self.find_partners_for_view
	# 	find(:all, :order => "id" )
	# end
	# has_many :measures
	# has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # # Include default devise modules. Others available are:
  # # :http_authenticatable, :token_authenticatable, :confirmable, :lockable, :timeoutable and :activatable
  # devise :registerable, :authenticatable, :recoverable,
  #        :rememberable, :trackable, :validatable

  # # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeding_process_controller.rb
class BreedingProcessController < ApplicationController
    def index
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end
end

app/controllers/dear_parents_controller.rb
class DearParentsController < ApplicationController
    def index
    end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
    def index
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
end

app/controllers/upbringing_controller.rb
class UpbringingController < ApplicationController
def index
	@partners = Partner.find_partners_for_view
end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title
        "Казкова долина"
    end 
    def tab(value)
        @page_tab = value
    end
end

app/views/breeding_process/index.html.erb
<div class="container">
<% tab "breeding_process" %>
  <%= render 'shared/header' %>
</div>

  <div class="container">
    <h1 align="center">Будні і свята</h1>
    <p>&nbsp;&nbsp;&nbsp;В дитячому оздоровчому закладі виховний процес здійснюється згідно плану виховної роботи табору та загонів. Протягом зміни в першій половині дня в таборі проводяться:</p>
    <div align="center"><br><%= image_tag("bantuk.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("malunku.jpg") %></div>
    <p>&nbsp;&nbsp;&nbsp;"Співаночки", конкурс емблем загонів та загонових куточків, конкурс фантастичних проектів, конкурс на кращий куточок живої природи "Краю мій лелечий", "Церемонія бантиків", конкурс малюнка, години спілкування "Поспілкуємось разом", працюють гуртки</p>
    <p>&nbsp;&nbsp;&nbsp;В другій половині дня проходять загальнодружинні заходи:</p>
    <p>&nbsp;&nbsp;&nbsp; - конкурс ділова гра "Лідер табору"</p>
    <p>&nbsp;&nbsp;&nbsp; - презентація загонів</p>
    <p>&nbsp;&nbsp;&nbsp; - інтелектуальна гра "Подорож в країну Сообразилію-Вообразилію"</p>
    <p>&nbsp;&nbsp;&nbsp; - конкурс акторської майстерності</p>
    <p>&nbsp;&nbsp;&nbsp; - театр екологічної моди</p>
    <div align="center"><br><%= image_tag("moda1.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("moda2.jpg") %></div>
    <p>&nbsp;&nbsp;&nbsp; - день самоврядування</p>
    <p>&nbsp;&nbsp;&nbsp; - веселі старти</p>
    <div align="center"><br><%= image_tag("veselistartu.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("veselistartu2.jpg") %></div>
    <p>&nbsp;&nbsp;&nbsp; - конкурс інсценованої казки</p>
    <p>&nbsp;&nbsp;&nbsp; - конкурс краси</p>
    <p>&nbsp;&nbsp;&nbsp; - веселий ярмарок</p>
    <p>&nbsp;&nbsp;&nbsp; - економічний день, аукціон</p>
    <p>&nbsp;&nbsp;&nbsp; - військово-спортивна гра "Десант"</p>
    <p>&nbsp;&nbsp;&nbsp; - закриття таборної зміни, вогнище, підведення підсумків</p>
  </div>

app/views/contact/index.html.erb
<div class="container">
<% tab "contact" %>
  <%= render 'shared/header' %>
</div>

<div class="container">
  <h1 align="center">Контактна інформація та географічне розташування</h1>

  <div align="center"><br><%= image_tag("mm.jpg") %></div></p>
  &nbsp;&nbsp;&nbsp;Директор: Михайло Миколайович Мартенюк - очолює оздоровчий заклад з 1987 року піклуючись про зміцнення та розширення її <a href="http://fairy-valley.vn.ua:3001/projects/show/8">бази</a><br><br>

  <h3 align="center">Як знайти</h3>
  <div align="center"><br><%= image_tag("map.jpg") %></div>

  <p>&nbsp;&nbsp;&nbsp;Адреса:<br>
  <p>22344, Вінницька обл., Літинський район, село Сосни.<br>
  ППНОДЗ “Казкова долина” код 04542011, <br>
  р/р 26003055301497 в ВФ КБ Приватбанк МФО 302689, м. Вінниця.<br>
  Телефон: (04347)-2-11-36</p>
</div>

app/views/dear_parents/index.html.erb
<div class="container">
<% tab "dear_parents" %>
  <%= render 'shared/header' %>
</div>

<div class="container">

    <h1 align="center">ШАНОВНІ БАТЬКИ!</h1>
    <p>&nbsp;&nbsp;&nbsp;Ваша дитина їде в дитячий оздоровчий заклад “Казкова долина” село Сосни Літинського району. "Казкова долина" розміщена в <%= link_to 'чудовому куточку Вінниччини', 'http://fairy-valley.vn.ua:3001/projects/show/2' %> в оточенні пишної багатої хвої і за 20 років свого існування стала відома серед дитячих оздоровчих закладів України.

    <div align="center"><br><%= image_tag("ov1.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("bir.jpg") %></div></p>

    <p>&nbsp;&nbsp;&nbsp;В заклад приймаються діти віком від 7 до 16 років (учні 1-10 класів).</p>

    <div align="center"><br><%= image_tag("dutunawelcome.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("bigchildren.jpg") %></div>

    <p>&nbsp;&nbsp;&nbsp;Не забудьте дати: одяг, (штани, спідницю, курточку...), спортивний одяг та взуття, дві зміни натуральної білизни, зубну щітку, пасту, мило.</p>
    <p>&nbsp;&nbsp;&nbsp;Підставою для приймання дитини в дитячий заклад є дана путівка та медичні довідки: про стан здоров'я, епідемокруження, профілактичні щеплення, від лікаря дерматолога (шкіра, педикульоз), від лікаря окуліста.</p>
    <p>&nbsp;&nbsp;&nbsp;Серед важливих факторів дитячого оздоровлення — повноцінне якісне харчування, яке в дитячому оздоровчому закладі 5-ти разове. Їжу готують висококваліфіковані кухарі, в меню цілий сезон — свіжі овочі та фрукти.</p>

    <div align="center"><br><%= image_tag("stolova1.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("stolova2.jpg") %></div>

    <p>&nbsp;&nbsp;&nbsp;	Путівку можна придбати безпосередньо в дитячому оздоровчому закладі “Казкова долина”, чи через фонди соціального страхування по місцю проживання. 
    <br>
    Проведенням грошових розрахунків за путівку здійснюється за такими банківськими реквізитами:</p>

    <p>22344, Вінницька обл., Літинський район, с. Сосни.<br>
    <b>ППНОДЗ “Казкова долина” код 04542011, <br>
    р/р 26003055301497 в ВФ КБ Приватбанк МФО 302689, м. Вінниця.<br>
    Телефон: (04347)-2-11-36</b></p>
    <p>Адміністрація дитячого оздоровчого закладу “Казкова долина” запрошує дітей і бажає приємного відпочинку, успішного перебування та цікавих вражень.</p>

    <div align="center"><br><%= image_tag("adminbuild.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("dituidut.jpg") %></div>


    <div align="center"><br><%= image_tag("all1.jpg") %><%= image_tag("all2.jpg") %><%= image_tag("all3.jpg") %></div>
</div>

app/views/history/index.html.erb
<div class="container">
<% tab "history" %>
  <%= render 'shared/header' %>
</div>

  <div class="container">
    <h1 align="center">Сторінки нашої історії</h1>

    <h3 align="center">Слово про архітектора</h3>
    <div align="Left">
        <p>&nbsp;&nbsp;&nbsp;Ви відпочиваєте у «Казковій долині», яка побудована за проектом Літинського художника-архітектора Леоніда Яковчука. </p>
        <p>&nbsp;&nbsp;&nbsp;Леонід Мечиславович Яковчук народився 28 серпня 1958 року у селі Ворошилівка Троянівського району Житомирської області. За фахом архітектор. Закінчив Одеський інженерно-технічний інститут. З 1978 по 1996 роки працював головним архітектором Літинського району. У березні 2005 року через тяжку хворобу його не стало. На Літинщині залишилось сім найяскравіших реалізованих архітектурних проектів автором яких є Леонід Яковчук.</p>
        <p>&nbsp;&nbsp;&nbsp;1.Казкова долина с. Сосни</p>
        <p>&nbsp;&nbsp;&nbsp;2.Меморіальний комплекс загиблим воїнам 1941-1945 роки у Літині</p>
        <p>&nbsp;&nbsp;&nbsp;3.Стадіон у Літині</p>
        <p>&nbsp;&nbsp;&nbsp;4.Парк культури та відпочинку у Літині</p>
        <p>&nbsp;&nbsp;&nbsp;5.Церква православних християн у с. Брусленів</p>
        <p>&nbsp;&nbsp;&nbsp;6.Церква адвентистів у Літині</p>
        <p>&nbsp;&nbsp;&nbsp;7.Середня школа у с. Вінниківцях</p>
    </div>
    <div align="center"><br><%= image_tag("ngisptahom.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("ptahusoncia1.jpg") %></div></p>
    <div align="Left">
        <p>&nbsp;&nbsp;&nbsp;Талановита і добра душею людина, яка в усі куточки України і світу направила у політ птахи щастя. Він хотів, щоб вам було тут радісно, щоб ви були щасливі. А сам захворів і залишив нас. Літинчани завжди пам'ятають і згадують його із глибокою вдячністю. Його робота і досі приносить радість людям.</p>
        <p>&nbsp;&nbsp;&nbsp;Ось що про свою творчість говорив сам Леонід Мечиславович: “Спочатку була архітектура. З нею були пов'язані всі плани та надії... і тоді прилетіли вони, птахи з різних казок та легенд виготовлені із дровин, що не стали паливом”.</p>
        <p>&nbsp;&nbsp;&nbsp;Птахи вирізьблені особливим методом із дерева і закріплені на полотні у відповідності із задуманим сюжетом надають картинам казкову незвичайність та рельєфність. Жодна з картин не схожа на іншу. Картини переносять нас у далекий світ, де панують добро і краса.</p>
    </div>

    <div align="center">
        <br><%= image_tag("ptahusoncia2.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("ptahusoncia3.jpg") %>
    </div> 

    <!--&nbsp;&nbsp;&nbsp;Історія сягає сивої давнини, коли були ось такі знамена
    <div align="center"><br><%= image_tag("text.jpg") %>&nbsp;&nbsp;&nbsp;<%= image_tag("znameno.jpg") %></div>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8"> 
    <title><%= full_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% render 'shared/menu' %>
    <div class="container">
        <%= yield %>
        <%= render 'shared/footer' %>

    </div>
  </body>
</html>

app/views/pages/index.html.erb
<% tab "home" %>
<div class="container">
  <%= render 'shared/header' %>
</div>

<div class="container">
    <%= image_tag("title_big.jpg") %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <small>
Пет проект по контенту 2010 року. Частково відновлена і доповнена версія.
  </small>
    <div class="container">
        &nbsp;&nbsp;&nbsp; &copy; Сергій Дудник 2010, <%= Time.now.year %>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    
    <nav>
      <ul class="nav nav-tabs navbar-right">
        <li class="nav-item">
          
          <%= link_to 'Головна', root_path, class: (@page_tab == "home"? "nav-link active" : "nav-link") %>

        </li>

        <li class="nav-item">
          <%= link_to 'Шановні батьки', dear_parents_path, class: (@page_tab == "dear_parents"? "nav-link active" : "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to "Будні і свята", breeding_process_path, class: (@page_tab == "breeding_process"? "nav-link active" : "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to 'Із історії', history_path, class: (@page_tab == "history"? "nav-link active" : "nav-link") %>
        </li>
        <li><%= link_to 'Контакти', contact_path, class: (@page_tab == "contact"? "nav-link active" : "nav-link") %></li>
        <li><%= link_to "Фотогалерея", '#', class: "nav-link" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_menu.html copy.erb
<!--
<ul>
    <li><%= link_to 'Головна', root_path %></li>
    <li><%= link_to 'Шановні батьки', dear_parents_path %></li>
    <li><%= link_to 'Будні і свята', breeding_process_path %></li>
    <li><%= link_to 'Із історії', history_path %></li>
    <li><%= link_to 'Контакти', contact_path %></li>
</ul>

<div id="side">
         <a href="upbringing">Наші гості</a><br />
         <a href="http://fairy-valley.vn.ua:3001">Фотогалерея</a><br />
</div> -->

app/views/shared/_menu.html.erb
<header class="navbar">
  <div class="container">
  <%= link_to "Казкова долина", root_path, id: "logo" %>
    <nav> 
      <ul class="nav nav-tabs">
          <li><%= link_to 'Шановні батьки', dear_parents_path, class: "nav-link" %></li>
          <li><%= link_to 'Будні і свята', breeding_process_path, class: "nav-link" %></li>
          <li><%= link_to 'Із історії', history_path, class: "nav-link" %></li>
          <li><%= link_to 'Контакти', contact_path, class: "nav-link" %></li>
      </ul>
    </nav>
  </div>
  </header>

app/views/upbringing/index.html.erb
<div id="banner">
<%= image_tag("title.jpg") %>
<%= @page_title || "Казкова долина" %>
</div>

<div id="columns">
<div id="side">
         <a href="/home/index">Головна</a><br />
         <a href="dear_parents">Шановні батьки</a><br />
         <a href="breeding_process">Будні і свята</a><br />
         <a href="history">Із історії</a><br />
         <a href="contact">Контакти</a><br />
         <a href="http://fairy-valley.vn.ua:3001">Фотогалерея</a><br />
</div>
<div id="main">
             <h1 align="center">Наші гості</h1>
             <div id="product-list">
             <table>
             <% for partner in @partners -%>
             <tr  class="<%= cycle('list-line-odd', 'list-line-even') %>">
                 <td><%= image_tag partner.photo.url(:medium) %></td>
                 <td>
                     <dl>
                             <dt><h3><%= partner.name %></h3></dt>
                             <dd><%= partner.description %></dd>
                     </dl>
                 </td>
             </tr>
<tr><td colspan="2">
<% partner.measures.each do |c| %>
<p>
 <% if partner.id == 1 && c.id == 3 %>
         <%=	link_to c.name, 'http://fairy-valley.vn.ua:3001/projects/show/4' %> <%=h c.date %>
     <% else %>
         <% if partner.id == 1 && c.id == 4 %>
             <%=	link_to c.name, 'http://fairy-valley.vn.ua:3001/projects/show/5' %> <%=h c.date %>
                 <% else %>
                     <% if partner.id == 1 && c.id == 11 %>
                         <%=	link_to c.name, 'http://fairy-valley.vn.ua:3001/projects/show/6' %> <%=h c.date %>
                             <% else %>
         <%=	h c.name %> <%=h c.date %>
     <% end %>
     <% end %>
     <% end %>
</p>
<% end %>
<td><tr>
             <% end %>
             </table>
             </div>
</div>
</div>